# Generated by Django 4.0.3 on 2022-03-10 12:49

from django.db import migrations

def create_data(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    Member(name="John Doe", email="doe@3mail.com", document="22342342", contact="333333").save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
